[RESEARCH] c++ compile,run and compare

diff --git a/compile/cpp b/compile/cpp
--- a/compile/cpp
+++ b/compile/cpp
@@ -39,8 +39,6 @@
 # other_codes are unknown to boca: in this case BOCA will present the
 #                                  last line of standard output to the judge
 
-umask 0022
-
 if [ "$1" == "" ]; then
     echo "parameter problem"
     exit 43
@@ -54,23 +52,10 @@ if [ ! -r "$1" ]; then
     echo "$1 not found or it's not readable"
     exit 44
 fi
-mkdir -p src
-if [ "${name##*.}" == "zip" -a "${name##*.}" == "ZIP" ]; then
-	unzip "$name" -d src
-	name="*.c"
-else
-	cp "$name" src
-fi
-id -u bocajail >/dev/null 2>/dev/null
-if [ $? == 0 ]; then
-	bocau=`id -u bocajail`
-	bocag=`id -g bocajail`
-	chown bocajail.nogroup .
-else
-	bocau=`id -u nobody`
-	bocag=`id -g nobody`
-	chown nobody.nogroup .
-fi
+
+bocau=`id -u`
+bocag=`id -g`
+
 if [ "$bocau" == "" -o "$bocag" == "" ]; then
 	echo "error finding user to run script"
 	exit 43
@@ -78,8 +63,9 @@ fi
 
 # this script makes use of safeexec to execute the code with less privilegies
 # make sure that directories below are correct.
-sf=`which safeexec`
-[ -x "$sf" ] || sf=/usr/bin/safeexec
+
+sf="`pwd`/safeexec"
+
 if [ ! -x $sf ]; then
     echo "$sf not found or it's not executable"
     exit 46
@@ -105,68 +91,40 @@ else
   exe=$2
 fi
 
-rm -f $exe compileit.retcode runit.retcode 2>/dev/null
-cat <<EOF > compileit.sh
-#!/bin/bash
-cc=\`which g++\`
-[ -x "\$cc" ] || cc=/usr/bin/g++
-if [ ! -x "\$cc" ]; then
-    echo "\$cc not found or it's not executable"
-    exit 47
-fi
-cd src
-"\$cc" -static -O2 -o ../$exe $name -lm
-echo \$? > ../compileit.retcode
-exit 0
-EOF
-chmod 755 compileit.sh
+rm -f $exe compileit.retcode runit.retcode stderr0  stdin0  stdout0 2>/dev/null
 
 cdir=`pwd`
 echo "Current directory is $cdir" >&2
-echo $cdir | grep -q "/bocajail"
-if [ $? == 0 ]; then
-    cdir=`echo $cdir | sed "s/.*\/bocajail//"`
-    echo "Internal directory is $cdir"
-    cat <<EOF > runit.sh
-#!/bin/bash
-cd "$cdir"
-[ -f /proc/cpuinfo ] || /bin/mount -t proc proc /proc
-#/bin/mount --bind /dev /dev
-[ -d /sys/kernel ] || /bin/mount -t sysfs sysfs /sys
-$sf -r1 -F1000 -n0 -U$bocau -G$bocag -C. -ostdout0 -estderr0 -d$maxm -m$maxm -f20000 -t$ttime -T$ttime ./compileit.sh
-echo \$? > runit.retcode
-if [ ! -d /bocajail ]; then
-  /bin/umount /proc 2>/dev/null
-  #/bin/umount /dev
-  /bin/umount /sys 2>/dev/null
+
+echo "COMPILATION IS NOT BEING CHROOTED -- THIS IS NOT AN IDEAL SETTING"
+#$sf -r1 -F1000 -n0 -U$bocau -G$bocag -C. -ostdout0 -estderr0 -d$maxm -m$maxm -f20000 -t$ttime -T$ttime ./compileit.sh
+
+cc=/usr/bin/g++
+if [ ! -x "$cc" ]; then
+    echo "$cc not found or it's not executable"
+    exit 47
 fi
-EOF
-    chmod 755 runit.sh
-    chroot /bocajail "$cdir/runit.sh"
-    if [ -r runit.retcode ]; then
-    	ret=`cat runit.retcode`
-    else
-		ret=99
-    fi
-else
-	echo "COMPILATION IS NOT BEING CHROOTED -- THIS IS NOT AN IDEAL SETTING"
-	$sf -r1 -F1000 -n0 -U$bocau -G$bocag -C. -ostdout0 -estderr0 -d$maxm -m$maxm -f20000 -t$ttime -T$ttime ./compileit.sh
-	ret=$?
-fi
+
+$cc -static -O2 -Wall -o $exe $name -lm 2> log
+ret=$?
+
 if [ -f "stdout0" ]; then
 	cat "stdout0"
 fi
 if [ -f "stderr0" ]; then
 	cat "stderr0"
 fi
-rm -rf src/
+
 if [ "$ret" != "0" ]; then
 	echo "Compilation Error: $ret"
-	exit $ret
+  cat log
+  exit $ret
 fi
-ret=`cat compileit.retcode`
-if [ "$ret" != "0" ]; then
-	echo "Compilation Error: $ret"
-	ret=1
-fi
+
+echo $ret
+cat log
+
+run/cpp $exe src/input2 1
+
+
 exit $ret
diff --git a/run/cpp b/run/cpp
--- a/run/cpp
+++ b/run/cpp
@@ -41,17 +41,9 @@
 # other_codes are unknown to boca: in this case BOCA will present the
 #                                  last line of standard output to the judge
 
-umask 0022
-id -u bocajail >/dev/null 2>/dev/null
-if [ $? == 0 ]; then
-	bocau=`id -u bocajail`
-	bocag=`id -g bocajail`
-	chown bocajail.nogroup .
-else
-	bocau=`id -u nobody`
-	bocag=`id -g nobody`
-	chown nobody.nogroup .
-fi
+bocau=`id -u`
+bocag=`id -g`
+
 if [ "$bocau" == "" -o "$bocag" == "" ]; then
 	echo "error finding user to run script"
 	exit 43
@@ -59,8 +51,7 @@ fi
 
 # this script makes use of safeexec to execute the code with less privilegies
 # make sure that directories below are correct.
-sf=`which safeexec`
-[ -x "$sf" ] || sf=/usr/bin/safeexec
+sf="`pwd`/safeexec"
 
 if [ "$1" == "" -o "$2" == "" -o "$3" == "" ]; then
     echo "parameter problem"
@@ -117,7 +108,7 @@ fi
 
 cdir=`pwd`
 echo "Current directory is $cdir -- chrooting on it" >&2
-$sf -F10 -f$maxf -r$nruns -n1 -R$cdir -C. -U$bocau -G$bocag -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 ./run.exe
+$sf -F10 -f$maxf -r$nruns -n0 -K -R$cdir -C. -U$bocau -G$bocag -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 ./run.exe
 ret=$?
 if [ $ret -gt 10 ]; then
 	ret=0
@@ -125,4 +116,14 @@ fi
 if [ -f stdout0 ]; then
   cat stdout0
 fi
+
+if [ "$ret" != "0" ]; then
+  echo "Compilation Error: $ret"
+  exit $ret
+else
+  echo "======= Successful Run ========"
+  echo "compare/cpp src/output2 stdout0"
+  compare/cpp src/output2 stdout0
+fi
+
 exit $ret
diff --git a/run/java b/run/java
--- a/run/java
+++ b/run/java
@@ -41,17 +41,9 @@
 # other_codes are unknown to boca: in this case BOCA will present the
 #                                  last line of standard output to the judge
 
-umask 0022
-id -u bocajail >/dev/null 2>/dev/null
-if [ $? == 0 ]; then
-	bocau=`id -u bocajail`
-	bocag=`id -g bocajail`
-	chown bocajail.nogroup .
-else
-	bocau=`id -u nobody`
-	bocag=`id -g nobody`
-	chown nobody.nogroup .
-fi
+bocau=`id -u`
+bocag=`id -g`
+
 if [ "$bocau" == "" -o "$bocag" == "" ]; then
 	echo "error finding user to run script"
 	exit 43
@@ -59,8 +51,7 @@ fi
 
 # this script makes use of safeexec to execute the code with less privilegies
 # make sure that directories below are correct.
-sf=`which safeexec`
-[ -x "$sf" ] || sf=/usr/bin/safeexec
+sf="`pwd`/safeexec"
 
 if [ "$1" == "" -o "$2" == "" -o "$3" == "" ]; then
     echo "parameter problem"
@@ -129,53 +120,21 @@ cp "$2" stdin0 2>/dev/null
 
 cdir=`pwd`
 echo "Current directory is $cdir" >&2
-echo $cdir | grep -q "/bocajail"
-if [ $? == 0 ]; then
-    cdir=`echo $cdir | sed "s/.*\/bocajail//"`
-    cat <<EOF > runit.sh
-#!/bin/bash
-cd "$cdir"
-[ -f /proc/cpuinfo ] || /bin/mount -t proc proc /proc
-#/bin/mount --bind /dev /dev
-[ -d /sys/kernel ] || /bin/mount -t sysfs sysfs /sys
+
+echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
 java=`which java`
-[ -x "\$java" ] || java=/usr/bin/java
-if [ ! -x \$java ]; then
-    echo "\$java not found or it's not executable"
-    exit 47
+[ -x "$java" ] || java=/usr/bin/java
+if [ ! -x $java ]; then
+  echo "$java not found or it's not executable"
+  exit 47
 fi
-export CLASSPATH=.:./run.jar:$CLASSPATH
-$sf -r$nruns -t$time -T$ttime -istdin0 -F256 -u256 -ostdout0 -estderr0 -U$bocau -G$bocag -n0 -C. -f20000 -d20000000 -m20000000 -- \$java -Xmx${maxm}K -Xms${maxm}K "$name"
-retval=\$?
-echo \$retval > runit.retcode
-if [ ! -d /bocajail ]; then
-  /bin/umount /proc 2>/dev/null
-  #/bin/umount /dev
-  /bin/umount /sys 2>/dev/null
-fi
-EOF
-    chmod 755 runit.sh
-    chroot /bocajail "$cdir/runit.sh"
-	if [ -r runit.retcode ]; then
-    	ret=`cat runit.retcode`
-	fi
-	if [ "$ret" == "" ]; then
-		echo "Execution error - check autojudging"
-		exit 49
-	fi
-else
-    echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-    echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-    echo "CODE NOT BEING CHROOTED. DO NOT RUN THIS ON THE MAIN SERVER" >&2
-	java=`which java`
-	[ -x "$java" ] || java=/usr/bin/java
-	if [ ! -x $java ]; then
-		echo "$java not found or it's not executable"
-		exit 47
-	fi
-	$sf -r$nruns -t$time -T$ttime -istdin0 -F256 -u256 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -d20000000 -m20000000 -- $java -cp run.jar -Xmx${maxm}K -Xms${maxm}K "$name"
-	ret=$?
-fi
+
+$sf -r$nruns -t$time -T$ttime -istdin0 -F256 -u256 -U$bocau -G$bocag -ostdout0 -estderr0 -n0 -C. -K -d20000000 -m20000000 -- $java -cp run.jar -Xmx${maxm}K -Xms${maxm}K "$name"
+ret=$?
+echo "==============="
+echo $ret
+echo "==============="
+
 if [ $ret -gt 10 ]; then
 	echo "> > > > > > > Nonzero return code - possible runtime error - I'M GUESSING IT IS RUNTIME ERROR < < < < < < < <"
 	ret=9
@@ -183,4 +142,5 @@ fi
 if [ -f stdout0 ]; then
   cat stdout0
 fi
+
 exit $ret
