[test] python judge

diff --git a/run/py b/run/py
--- a/run/py
+++ b/run/py
@@ -15,13 +15,15 @@
 # //    You should have received a copy of the GNU General Public License
 # //    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 # ////////////////////////////////////////////////////////////////////////////////
-#Last modified: 21/july/2012 by cassio@ime.usp.br
+#Last modified: 22/aug/2012 by cassio@ime.usp.br
 #
 # parameters are:
-# $1 source_file
-# $2 exe_file (default run.py)
-# $3 timelimit (optional, limit to run all the repetitions, by default only one repetition)
-# $4 maximum allowed memory (in MBytes, default 512M)
+# $1 exe_file
+# $2 input_file
+# $3 timelimit (limit to run all the repetitions, by default only one repetition)
+# $4 number_of_repetitions_to_run (optional, can be used for better tuning the timelimit)
+# $5 maximum allowed memory (in MBytes)
+# $6 maximum allowed output size (in KBytes)
 #
 # the output of the submission should be directed to the standard output
 #
@@ -39,81 +41,81 @@
 # other_codes are unknown to boca: in this case BOCA will present the
 #                                  last line of standard output to the judge
 
-#umask 0022
-
-if [ "$1" == "" ]; then
-    echo "parameter problem"
-    exit 43
-fi
-if [ ! -r "$1" ]; then
-    echo "$1 not found or it's not readable"
-    exit 44
-fi
-name="$1"
-if [ ! -r "$1" ]; then
-    echo "$1 not found or it's not readable"
-    exit 44
-fi
-
-
 bocau=`id -u`
 bocag=`id -g`
 
-if [ "$bocau" == "" -o "$bocag" == "" ]; then
-	echo "error finding user to run script"
-	exit 43
-fi
-
-# this script makes use of safeexec to execute the code with less privilegies
-# make sure that directories below are correct.
 sf="`pwd`/safeexec"
 
-maxm=512000
+if [ "$1" == "" -o "$2" == "" -o "$3" == "" ]; then
+    echo "parameter problem"
+    exit 43
+fi
+
+if [ ! -x "$1" ]; then
+    echo "$1 not found (or is not in the current dir) or it's not executable"
+    exit 44
+fi
+if [ ! -r "$2" ]; then
+    echo "$2 not found (or is not in the current dir) or it's not readable"
+    exit 45
+fi
+if [ ! -x $sf ]; then
+    echo "$sf not found or it's not executable"
+    exit 46
+fi
+
+time=$3
+if [ "$time" -gt "0" ]; then
+  let "ttime = $time + 30"
+else
+  time=1
+  ttime=30
+fi
+
+nruns=1
 if [ "$4" != "" ]; then
   if [ "$4" -gt "0" ]; then
-    maxm=${4}000
+    nruns=$4
+  fi
+fi
+maxm=512000
+if [ "$5" != "" ]; then
+  if [ "$5" -gt "0" ]; then
+    maxm=${5}000
+  fi
+fi
+maxf=1024
+if [ "$6" != "" ]; then
+  if [ "$6" -gt "0" ]; then
+    maxf=${6}
   fi
 fi
 
-# setting up the timelimit according to the problem
-if [ "$3" == "" ]; then
-  time=5
-else
-  time=$3
-fi
-let "ttime = $time + 30"
+cp "$2" stdin0 2>/dev/null
+cp "$1" run.py 2>/dev/null
 
-if [ "$2" == "" ]; then
-  exe=run.py
-else
-  exe=$2
-fi
-
-rm -f $exe compileit.retcode runit.retcode stderr0  stdin0  stdout0 2>/dev/null
 cdir=`pwd`
-echo "Current directory is $cdir" >&2
+chmod +x run.py
+rm -f stderr0 stdout0 2>/dev/null
 
-/usr/bin/python2 -c "__import__('compiler').parse(open('$name').read())" 2> log
+echo "Current directory is $cdir -- chrooting on it" >&2
+#$sf -F10 -f$maxf -r$nruns -n0 -R$cdir -C. -U$bocau -G$bocag -K -ostdout0 -estderr0 -d$maxm -m$maxm -t$time -T$ttime -istdin0 ./run.py
+$sf -F10 -n0 -R$cdir -C. -U$bocau -G$bocag -K -ostdout0 -estderr0 -t$time -T$ttime -istdin0 ./run.py
 ret=$?
-/usr/bin/python2 -c "import shutil; shutil.copy2('$name', '$exe')"
-
-if [ -f "stdout0" ]; then
-	cat "stdout0"
+if [ $ret -gt 10 ]; then
+	ret=0
 fi
-if [ -f "stderr0" ]; then
-	cat "stderr0"
+if [ -f stdout0 ]; then
+  cat stdout0
 fi
 
 if [ "$ret" != "0" ]; then
-	echo "Compilation Error: $ret"
-  cat log
-	exit $ret
+  echo "Compilation Error: $ret"
+  exit $ret
 else
-  cat log
-  echo "======= Successful compilation ========"
-  echo "run/py $exe src/input2 1"
-  run/py $exe src/input2 1
+  echo "======= Successful Run ========"
+  echo "compare/py src/output2 stdout0"
+  compare/py src/output2 stdout0
 fi
-
 
 exit $ret
